### PR TITLE
Remove emberconf specifics

### PR DESCRIPTION
**Pull request by bryanhickerson**
Remove emberconf specific content

Summary
* Remove emberconf specific links
* Link to emberjs seattle github community
* Fix Help Wanted link

### CODE REVIEW

**Comment by jenweber** [comment]
Hi @bryanhickerson! I’m curious if you are running a workshop. Let me know if you need any help! Also we’d accept a PR to make this more generic someday. I meant to get to it myself but haven’t had the time.

Good luck!

cc @locks

**Comment by bryanhickerson** [comment]
Yep, the Seattle meetup is going to have a workshop next week! I didn’t
actually mean to open a pr against your repo, but it makes sense to merge
in some of the changes to make it more generic. I added some Seattle meetup
specific stuff, but I can cherry pick the general changes and submit a new
pr.

**Comment by jenweber** [comment]
That's awesome! @bryanhickerson which day is your workshop? We don't have a ton of help wanted issues at the moment, so I could make some more if you think that people would want to work on learning team stuff. We have a ton of work that always needs to be done, but sometimes get behind on writing it up.

**Comment by bryanhickerson** [comment]
It’s next Wednesday, so it’s kind of last minute, but if you’re able to tag
more issues that would be amazing.

**Comment by jenweber** [comment]
Cool, please make sure to include [ember-styleguide](https://github.com/ember-learn/ember-styleguide/issues) in your list. It is the #1 source of help wanteds and some of them are really fun and interesting. That repository is components that are used across the Ember websites.

Any others I add will be in [Ember.js source](https://github.com/emberjs/ember.js) (for API documentation) or the [https://github.com/emberjs/website](website) repo. We are in the middle of trying to move The Guides to a fresh new app. So, I'm not going to open new issues there, but if people are excited to work on the Guides, there will be issues in the [guides-app](https://github.com/ember-learn/guides-app) repo in the near future :)

Added issues:
- https://github.com/emberjs/ember.js/issues/16518

**Comment by bryanhickerson** [comment]
Awesome, thanks for all the tips! I should have reached out!

**Pull request closed without merging**
